---
- name: Check if Docker is already present
  command: which docker
  failed_when: false
  changed_when: false
  register: dockerpresence

- name: Download Docker install
  get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: 0775
  when: dockerpresence.rc == 1

- name: Run Docker install script
  shell: /tmp/get-docker.sh
  environment:
    CHANNEL: stable
  when: dockerpresence.rc == 1

- name: Ensure Docker has correct version
  apt:
    name: docker-ce
    state: present
    force: yes

- name: Ensure Docker is started
  service:
    name: docker
    state: started
    enabled: yes
