---
- name: Create cert-manager namespace
  become: yes
  k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: cert-manager
    api_version: v1
    kind: Namespace
    state: present

- get_url:
    url: https://github.com/jetstack/cert-manager/releases/download/{{ k3s_certmanager_version }}/cert-manager.yaml
    dest: /tmp/cert-manager-{{ k3s_certmanager_version }}.yaml
    mode: '0440'
  register: certmanagerdeployment
  

- name: Deploy cert-manager
  become: yes
  shell: kubectl apply -f /tmp/cert-manager-{{ k3s_certmanager_version }}.yaml
  when: certmanagerdeployment.changed
  # Would rather prefer to use this
  #k8s:
  #  kubeconfig: /etc/rancher/k3s/k3s.yaml
  #  state: present
  #  src: /tmp/cert-manager.yaml

- copy:
    src: kubernetes/cluster-issuer.yaml
    dest: /tmp/cluster-issuer.yaml
    owner: pi
    group: pi
    mode: '0644'

- name: Deploy cluster issuer
  become: yes
  k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    src: /tmp/cluster-issuer.yaml
