---
nextcloud_k3s_namespace: 'nextcloud'
nextcloud_k3s_secret_name: 'nextcloud-secrets'
nextcloud_domain: 'next.lokalvert.tech'
nextcloud_version: '15.0'
nextcloud_database_name: 'nextcloud'
nextcloud_postgres_version: '12.1'
