- hosts: masters
  become: yes

  roles:
    - {role: pi-base-setup}
    - {role: pi-prepare-containerization}
    - {role: pi-security}
    - {role: pi-k3s-setup}

  tasks:
  - name: Setup k3s
    import_tasks: tasks/k3s_master.yml
