- hosts: masters
  become: yes

  vars:
    k3s_master_host: 'https://192.168.0.105:6443'

  roles:
    - {role: pi-base-setup}
    - {role: pi-prepare-containerization}
    - {role: pi-security}

  tasks:
  - debug:
      msg:
        - "Configuring this host as k8s master node"

  - name: Setup k3s
    import_tasks: tasks/k3s_master.yml

  - name: Configure cluster
    import_tasks: tasks/k3s_certmanager.yml
