- hosts: masters
  become: yes

  roles:
  - role: pi-k3s-certmanager
    vars:
      k3s_certmanager_version: 'v0.12.0'
  - role: pi-k3s-ingress-controller
    vars:
      k3s_traefik_version: '1.77.1'
  - { role: pi-k3s-logging }
  - role: pi-k3s-nextcloud
    vars:
      nextcloud_version: '15.0'
      nextcloud_postgres_version: '12.1'
