---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install NTFS support
  apt:
    name: ntfs-3g
    state: present

- name: Install some base packages ⑦
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - vim
    - aptitude
    - git

# Install Python2 pip for legacy reasons
- name: Install pip
  apt:
    name: python-pip
    state: present

# Prefer to use Python3's pip
# Also used by ansible
- name: Install pip 3
  apt:
    name: python3-pip
    state: present

- name: Install python dependencies
  pip:
    name: ['setuptools', 'openshift', 'PyYAML']
