---
- name: Check if k3s service exists
  stat: path=/etc/systemd/system/k3s.service
  register: k3sstat # use k3sstat.stat.exists to verify

- name: Bootstrap k3s
  shell: curl -sfL https://get.k3s.io | sh -
  when: not k3sstat.stat.exists

- name: Ensure k3s service is running
  systemd:
    state: restarted
    name: k3s
    enabled: yes
 
# Simplifies management of k3s
- name: Install k3sup
  become: yes
  shell: curl -sLS https://get.k3sup.dev | sh && sudo install k3sup /usr/local/bin/
  ignore_errors: yes
