---
- name: Create {{ k3s_logging_namespace }} namespace
  become: yes
  k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: '{{ k3s_logging_namespace }}'
    api_version: v1
    kind: Namespace
    state: present

- name: Copy logging manifests
  template:
    src: files/manifests/{{ item }}
    dest: /tmp/{{ item }}
    owner: pi
    group: pi
    mode: '0644'
  with_items:
  - 'elasticsearch-opendistro.yaml'

- name: Deploy manifests
  become: yes
  k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    src: '/tmp/{{ item }}'
  with_items:
  - 'elasticsearch-opendistro.yaml'
