kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sql-server-pvc
  namespace: sql-server
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server
  namespace: sql-server
  labels:
    app: sql-server
spec:
  selector:
    matchLabels:
      app: sql-server
  replicas: 1
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2017-latest
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-server
                  key: SA_PASSWORD
          volumeMounts:
            - name: db-staging-volume
              mountPath: /var/opt/mssql
      volumes:
        - name: db-staging-volume
          persistentVolumeClaim:
            claimName: sql-server-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sql-server
  namespace: sql-server
spec:
  selector:
    app: sql-server
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
